site_name: "NGSI Go"
site_description: NGSI Go (Let's FIWARE)

nav:
  - 'Home':
    - 'Index': index.md
    - 'Usage': usage.md
    - 'Quick Start Guide': quick_start_guide.md
    - 'Install': install.md
    - 'Build from source': build_source.md
    - 'files': files.md
    - 'APIs mapping table': apis_mapping_table.md
  - 'Convenience command':
    - 'admin':
      - 'admin': convenience/admin.md
      - 'appenders': convenience/appenders.md
      - 'loggers': convenience/loggers.md
      - 'scorpio': convenience/scorpio.md
    - 'apis': convenience/apis.md
    - 'cp': convenience/cp.md
    - 'wc': convenience/wc.md
    - 'man': convenience/man.md
    - 'health': convenience/health.md
    - 'ls': convenience/ls.md
    - 'receiver': convenience/receiver.md
    - 'regproxy': convenience/regproxy.md
    - 'rm': convenience/rm.md
    - 'template': convenience/template.md
    - 'version': convenience/version.md
  - 'NGSI command':
    - 'append': ngsi/append.md
    - 'create': ngsi/create.md
    - 'delete': ngsi/delete.md
    - 'get': ngsi/get.md
    - 'list': ngsi/list.md
    - 'replace': ngsi/replace.md
    - 'update': ngsi/update.md
    - 'upsert': ngsi/upsert.md
  - 'Time series commnad':
    - 'hdelete': time_series/hdelete.md
    - 'hget': time_series/hget.md
  - 'Cygnus':
    - 'groupingrules': cygnus/groupingrules.md
    - 'namemappings': cygnus/namemappings.md
  - 'IoT Agent commnad':
    - 'services': iot_agent/services.md
    - 'devices': iot_agent/devices.md
  - 'Context-Aware CEP':
    - 'rules': cep/rules.md
  - 'Keyrock':
    - 'users': keyrock/users.md
    - 'organizations':
      - 'organizations': keyrock/organizations.md
      - 'users': keyrock/organizations-users.md
    - 'applications':
      - 'applications': keyrock/applications.md
      - 'users': keyrock/users.md
      - 'roles': keyrock/applications-roles.md
      - 'permissions': keyrock/applications-permissions.md
      - 'organizations': keyrock/applications-organizations.md
      - 'pep-proxies': keyrock/applications-pep-proxies.md
      - 'iot-agent': keyrock/applications-iot-agent.md
      - 'trusted-applications': keyrock/applications-trusted-applications.md
    - 'providers': keyrock/providers.md
  - 'Management command':
    - 'broker': management/broker.md
    - 'context': management/context.md
    - 'settings': management/settings.md
    - 'server': management/server.md
    - 'token': management/token.md
  - 'Global Options': global.md
  - 'NGSI Go tutorial':
    - 'Index': tutorial/index.md
    - 'NGSI-LD CRUD': tutorial/ngsi-ld-crud.md
    - 'NGSIv2 CRUD': tutorial/ngsi-v2-crud.md
    - 'STH-Comet': tutorial/comet.md
    - 'QuantumLeap': tutorial/quantumleap.md
    - 'iot-agent': tutorial/iot-agent.md
    - 'perseo': tutorial/perseo.md
    - 'keyrock': tutorial/keyrock.md
    - 'keystone': tutorial/keystone.md

plugins:
    - search:
        lang: en
theme:
    name: readthedocs
    navigation_depth: 2

markdown_extensions:
#    - markdown_github.headerid
    - pymdownx.emoji
    - pymdownx.superfences
