name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: build test

    runs-on: ubuntu-latest

    env:
      TZ: Asia/Tokyo

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Checkout dependencies
      run: |
        go get github.com/x-motemen/gobump/cmd/gobump
        make devel-deps

    - name: Build NGSI Go
      run: make build
