version: "3"

services:
  geoproxy:
    image: letsfiware/geoproxy:1.0
    build: ./
    depends_on:
      - nginx

  nginx:
    image: nginx:1.19.10
    ports:
      - 1026:1026
      - 1030:1030
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - orion

  orion:
    image: fiware/orion:3.1.0
    depends_on:
      - mongo
    command: -dbhost mongo

  mongo:
    image: mongo:4.4
    command: --nojournal

